### ISSUE TITLE
Backing up seed phrase without microSD cards

### ISSUE THREAD

**Issue by blitzpsych** [digitalbitbox/bitbox02-firmware#1074]
I was looking at the [changelog.md](https://github.com/digitalbitbox/bitbox02-firmware/blob/master/CHANGELOG.md) for the master branch. I noticed that for firmware v9.13.0, the changelog states _"Allow skipping the microSD card backup in favor of backing up using the recovery words"_. I was not able to get the BitBox to setup (post-reset) without being prompted for adding a microSD card. Is the feature enabled in the above firmware? Or am I'm not executing the setup steps correctly?

I'm currently on the app version 4.37.0 built for MacOS(ARM) and Bitbox firmware v9.14.0.

Edit: Add the current Bitbox firmware version

**Comment by benma** [comment]
The firmware used to enforce the initial sdcard backup, but since v9.13.0 it is relaxed to enforce either the sdcard backup or the 24 words backup.

The BitBoxApp does not expose this functionality yet, but we are working on it, so a future version of the BitBoxApp will let you choose.

If you feel adventurous you can use the send_message.py CLI tool of this repo to create a wallet without making an sdcard backup.

Hope this helps.
